"""All status / type vocabularies in one place (shared by ORM models, schemas, contracts)."""

from enum import Enum


class CaseStatus(str, Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class DocumentProcessingStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    UNKNOWN = "UNKNOWN"


class FactType(str, Enum):
    ARREST_DATE = "ARREST_DATE"
    CUSTODY_START_DATE = "CUSTODY_START_DATE"
    REMAND_PERIOD = "REMAND_PERIOD"
    CHARGE_SHEET_DATE = "CHARGE_SHEET_DATE"
    COURT_ORDER = "COURT_ORDER"
    HEARING_DATE = "HEARING_DATE"
    FIR_REFERENCE = "FIR_REFERENCE"
    STATUTORY_SECTION = "STATUTORY_SECTION"
    OTHER = "OTHER"


class ConflictType(str, Enum):
    CONTRADICTION = "CONTRADICTION"
    DUPLICATE_EVIDENCE = "DUPLICATE_EVIDENCE"
    AMBIGUOUS_FACT = "AMBIGUOUS_FACT"
    WEAKLY_SUPPORTED = "WEAKLY_SUPPORTED"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ResolutionStatus(str, Enum):
    UNRESOLVED = "UNRESOLVED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"


class RunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TriggerType(str, Enum):
    MANUAL = "MANUAL"
    NEW_DOCUMENT = "NEW_DOCUMENT"
    RETRY = "RETRY"


class StageStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"


class RuleEvaluationStatus(str, Enum):
    EVALUATED = "EVALUATED"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    ERROR = "ERROR"


class ReviewSignal(str, Enum):
    """Neutral labels only. Never a grant/refusal of bail."""

    POTENTIAL_REVIEW_SIGNAL = "POTENTIAL_REVIEW_SIGNAL"
    NEEDS_HUMAN_REVIEW = "NEEDS_HUMAN_REVIEW"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"
    CONFLICTS_DETECTED = "CONFLICTS_DETECTED"
    ANALYSIS_INCOMPLETE = "ANALYSIS_INCOMPLETE"


class ReviewStatus(str, Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    IN_REVIEW = "IN_REVIEW"
    ADDITIONAL_INFORMATION_REQUESTED = "ADDITIONAL_INFORMATION_REQUESTED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"


class WorkflowAction(str, Enum):
    NONE = "NONE"
    CONTINUE_REVIEW = "CONTINUE_REVIEW"
    REQUEST_ADDITIONAL_INFORMATION = "REQUEST_ADDITIONAL_INFORMATION"
    ESCALATE_TO_SENIOR_REVIEWER = "ESCALATE_TO_SENIOR_REVIEWER"
    COMPLETE_REVIEW = "COMPLETE_REVIEW"


class AuditEventType(str, Enum):
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    DOCUMENT_REGISTERED = "DOCUMENT_REGISTERED"
    DOCUMENT_PROCESSING_STARTED = "DOCUMENT_PROCESSING_STARTED"
    DOCUMENT_PROCESSING_COMPLETED = "DOCUMENT_PROCESSING_COMPLETED"
    DOCUMENT_PROCESSING_FAILED = "DOCUMENT_PROCESSING_FAILED"
    EVIDENCE_STORED = "EVIDENCE_STORED"
    CONFLICTS_STORED = "CONFLICTS_STORED"
    RULE_RESULTS_STORED = "RULE_RESULTS_STORED"
    ANALYSIS_RUN_CREATED = "ANALYSIS_RUN_CREATED"
    ANALYSIS_RUN_STARTED = "ANALYSIS_RUN_STARTED"
    ANALYSIS_STAGE_COMPLETED = "ANALYSIS_STAGE_COMPLETED"
    ANALYSIS_STAGE_FAILED = "ANALYSIS_STAGE_FAILED"
    ANALYSIS_RUN_COMPLETED = "ANALYSIS_RUN_COMPLETED"
    ANALYSIS_RUN_PARTIALLY_COMPLETED = "ANALYSIS_RUN_PARTIALLY_COMPLETED"
    ANALYSIS_RUN_FAILED = "ANALYSIS_RUN_FAILED"
    ANALYSIS_RERUN_TRIGGERED = "ANALYSIS_RERUN_TRIGGERED"
    ANALYSIS_MARKED_STALE = "ANALYSIS_MARKED_STALE"
    REVIEW_CREATED = "REVIEW_CREATED"
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_UPDATED = "REVIEW_UPDATED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    ADDITIONAL_INFORMATION_REQUESTED = "ADDITIONAL_INFORMATION_REQUESTED"
