"""initial schema

Creates every CourtLens table. Enum columns are VARCHAR + one named CHECK constraint each
(portable to PostgreSQL; no native enum types).

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 03:15:18.790690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('fir_number', sa.String(length=100), nullable=True),
    sa.Column('police_station', sa.String(length=200), nullable=True),
    sa.Column('court_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('statutory_sections', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'CLOSED', 'ARCHIVED', name='status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('analysis_needs_refresh', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'UNDER_REVIEW', 'CLOSED', 'ARCHIVED')", name=op.f('ck_cases_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('external_reference', name=op.f('uq_cases_external_reference'))
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_fir_number'), ['fir_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'NEW_DOCUMENT', 'RETRY', name='trigger_type', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED', name='status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('current_stage', sa.String(length=60), nullable=True),
    sa.Column('requested_modules', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.Column('parent_run_id', sa.String(length=40), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('input_documents', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=40), nullable=False),
    sa.Column('agent_versions', sa.JSON(), nullable=False),
    sa.Column('output_refs', sa.JSON(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED', 'CANCELLED')", name=op.f('ck_analysis_runs_status')),
    sa.CheckConstraint("trigger_type IN ('MANUAL', 'NEW_DOCUMENT', 'RETRY')", name=op.f('ck_analysis_runs_trigger_type')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_analysis_runs_attempt_positive')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_analysis_runs_case_id_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_runs_parent_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs')),
    sa.UniqueConstraint('case_id', 'idempotency_key', name='uq_analysis_runs_case_idempotency')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_input_fingerprint'), ['input_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_status'), ['status'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='processing_status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.CheckConstraint("processing_status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED')", name=op.f('ck_documents_processing_status')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_documents_size_non_negative')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_documents_version_positive')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_documents_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('case_id', 'filename', 'version', name='uq_documents_case_filename_version')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_case_checksum', ['case_id', 'checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_processing_status'), ['processing_status'], unique=False)

    op.create_table('analysis_stages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('stage_name', sa.String(length=60), nullable=False),
    sa.Column('agent_key', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'SKIPPED', 'NOT_CONFIGURED', 'NOT_IMPLEMENTED', name='status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('output_run_id', sa.String(length=40), nullable=True),
    sa.Column('carried_over', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'SKIPPED', 'NOT_CONFIGURED', 'NOT_IMPLEMENTED')", name=op.f('ck_analysis_stages_status')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_analysis_stages_attempts_non_negative')),
    sa.ForeignKeyConstraint(['output_run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_stages_output_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], name=op.f('fk_analysis_stages_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_stages')),
    sa.UniqueConstraint('run_id', 'stage_name', name='uq_analysis_stages_run_stage')
    )
    with op.batch_alter_table('analysis_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_stages_run_id'), ['run_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=60), nullable=True),
    sa.Column('analysis_run_id', sa.String(length=40), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_audit_events_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_audit_events_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_audit_events_case_time', ['case_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=40), nullable=False),
    sa.Column('conflict_type', sa.Enum('CONTRADICTION', 'DUPLICATE_EVIDENCE', 'AMBIGUOUS_FACT', 'WEAKLY_SUPPORTED', 'MISSING_EVIDENCE', name='conflict_type', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity', native_enum=False, create_constraint=False, length=40), nullable=True),
    sa.Column('related_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('related_document_ids', sa.JSON(), nullable=False),
    sa.Column('conflicting_values', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.Enum('UNRESOLVED', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='resolution_status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.CheckConstraint("conflict_type IN ('CONTRADICTION', 'DUPLICATE_EVIDENCE', 'AMBIGUOUS_FACT', 'WEAKLY_SUPPORTED', 'MISSING_EVIDENCE')", name=op.f('ck_conflicts_conflict_type')),
    sa.CheckConstraint("resolution_status IN ('UNRESOLVED', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')", name=op.f('ck_conflicts_resolution_status')),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_conflicts_severity')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_conflicts_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_conflicts_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflicts'))
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_conflict_type'), ['conflict_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_resolution_status'), ['resolution_status'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('fact_type', sa.String(length=60), nullable=False),
    sa.Column('fact_value', sa.JSON(), nullable=False),
    sa.Column('entity_ref', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'UNKNOWN', name='verification_status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('extracted_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('extraction_run_id', sa.String(length=40), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.CheckConstraint("verification_status IN ('VERIFIED', 'UNVERIFIED', 'UNKNOWN')", name=op.f('ck_evidence_verification_status')),
    sa.CheckConstraint('(char_start IS NULL AND char_end IS NULL) OR (char_start IS NOT NULL AND char_end IS NOT NULL AND char_start >= 0 AND char_end >= char_start)', name=op.f('ck_evidence_offsets_valid')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_evidence_confidence_range')),
    sa.CheckConstraint('source_page IS NULL OR source_page >= 1', name=op.f('ck_evidence_page_positive')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_evidence_case_id_cases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_evidence_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['analysis_runs.id'], name=op.f('fk_evidence_extraction_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_extraction_run_id'), ['extraction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_fact_type'), ['fact_type'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=40), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'IN_REVIEW', 'ADDITIONAL_INFORMATION_REQUESTED', 'REVIEW_COMPLETED', name='status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('workflow_action', sa.Enum('NONE', 'CONTINUE_REVIEW', 'REQUEST_ADDITIONAL_INFORMATION', 'ESCALATE_TO_SENIOR_REVIEWER', 'COMPLETE_REVIEW', name='workflow_action', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('reviewed_finding_refs', sa.JSON(), nullable=False),
    sa.Column('additional_evidence_requested', sa.Boolean(), nullable=False),
    sa.Column('additional_information_request', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("status IN ('PENDING_REVIEW', 'IN_REVIEW', 'ADDITIONAL_INFORMATION_REQUESTED', 'REVIEW_COMPLETED')", name=op.f('ck_reviews_status')),
    sa.CheckConstraint("workflow_action IN ('NONE', 'CONTINUE_REVIEW', 'REQUEST_ADDITIONAL_INFORMATION', 'ESCALATE_TO_SENIOR_REVIEWER', 'COMPLETE_REVIEW')", name=op.f('ck_reviews_workflow_action')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_reviews_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_reviews_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_status'), ['status'], unique=False)

    op.create_table('rule_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=40), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('evaluation_status', sa.Enum('EVALUATED', 'INSUFFICIENT_INFORMATION', 'NOT_APPLICABLE', 'ERROR', name='evaluation_status', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('input_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('review_signal', sa.Enum('POTENTIAL_REVIEW_SIGNAL', 'NEEDS_HUMAN_REVIEW', 'INSUFFICIENT_INFORMATION', 'CONFLICTS_DETECTED', 'ANALYSIS_INCOMPLETE', name='review_signal', native_enum=False, create_constraint=False, length=40), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('missing_prerequisites', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('output_schema_version', sa.String(length=20), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.CheckConstraint("evaluation_status IN ('EVALUATED', 'INSUFFICIENT_INFORMATION', 'NOT_APPLICABLE', 'ERROR')", name=op.f('ck_rule_results_evaluation_status')),
    sa.CheckConstraint("review_signal IN ('POTENTIAL_REVIEW_SIGNAL', 'NEEDS_HUMAN_REVIEW', 'INSUFFICIENT_INFORMATION', 'CONFLICTS_DETECTED', 'ANALYSIS_INCOMPLETE')", name=op.f('ck_rule_results_review_signal')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], name=op.f('fk_rule_results_analysis_run_id_analysis_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_rule_results_case_id_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_results')),
    sa.UniqueConstraint('analysis_run_id', 'rule_id', 'rule_version', name='uq_rule_results_run_rule_version')
    )
    with op.batch_alter_table('rule_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_results_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_results_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_results_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_results_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_results_case_id'))
        batch_op.drop_index(batch_op.f('ix_rule_results_analysis_run_id'))

    op.drop_table('rule_results')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_reviews_case_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_analysis_run_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_fact_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_extraction_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_document_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_resolution_status'))
        batch_op.drop_index(batch_op.f('ix_conflicts_conflict_type'))
        batch_op.drop_index(batch_op.f('ix_conflicts_case_id'))
        batch_op.drop_index(batch_op.f('ix_conflicts_analysis_run_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_correlation_id'))
        batch_op.drop_index('ix_audit_events_case_time')
        batch_op.drop_index(batch_op.f('ix_audit_events_case_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_analysis_run_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('analysis_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_stages_run_id'))

    op.drop_table('analysis_stages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_processing_status'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))
        batch_op.drop_index('ix_documents_case_checksum')

    op.drop_table('documents')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_parent_run_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_input_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_case_id'))

    op.drop_table('analysis_runs')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_fir_number'))

    op.drop_table('cases')
    # ### end Alembic commands ###
